CREATE TABLE IF NOT EXISTS gb_classes(
	ClassID INT UNSIGNED NOT NULL AUTO_INCREMENT,
	class VARCHAR(16) NOT NULL,
	body VARCHAR(24) NOT NULL,
	front VARCHAR(256),
	side VARCHAR(256),
	back VARCHAR(256),
	PRIMARY KEY(ClassID)
)ENGINE=InnoDB CHARACTER SET utf8;

CREATE TABLE IF NOT EXISTS gb_lineup(
	PageID INT UNSIGNED NOT NULL,
	SortID INT(4) UNSIGNED NOT NULL DEFAULT 0,
	ClassID INT UNSIGNED NOT NULL,
	ModelID VARCHAR(64) NOT NULL,
	SetID INT UNSIGNED,
	published ENUM('Not published','Published') NOT NULL DEFAULT 'Not published',
	language ENUM('uk','ru') NOT NULL DEFAULT 'uk',
	model VARCHAR(48) NOT NULL,
	cover VARCHAR(256) NOT NULL DEFAULT '/images/NIA.jpg',
	profile VARCHAR(256),
	PRIMARY KEY(PageID),
	FOREIGN KEY (PageID) REFERENCES gb_pages(PageID)
		ON UPDATE CASCADE
		ON DELETE CASCADE,
	FOREIGN KEY (ClassID) REFERENCES gb_classes(ClassID)
		ON UPDATE CASCADE
		ON DELETE CASCADE,
	FOREIGN KEY (SetID) REFERENCES gb_media(SetID)
		ON UPDATE CASCADE
		ON DELETE SET NULL,
	UNIQUE(language,ModelID)
)ENGINE=InnoDB CHARACTER SET utf8;